version: 2.1

jobs:
  run-aikio-scan:
    docker: # executor type
      - image: cimg/base:2021.07

    steps:
      - setup_remote_docker:
          # cache docker layers on staging
          docker_layer_caching: true
      - run:
          name: "Install Docker"
          command: docker --help
      - run:
          name: "Run Aikido scan"
          command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aikidosecurity/local-scanner image-scan node:8.0.0 --apikey AIK_CI_xu6VkpGlaVW2UhoJinaVmGIalHG92Ak3h7zTT5DUXo0RqGprNaVkOiTzhR2I4Dsw
workflows:
  my-workflow:
    jobs:
      - run-aikio-scan:
          filters:
            branches:
              only:
                - master
